[package]
name = "sqlx-utils-macro"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = { version =  "2.0", features = ["full"] }
syn_derive = { version = "0.2.0", features = ["full"] }

[features]
default = ["any"]
sqlite = []
any = []
postgres = []
mysql = []
